### ISSUE TITLE
ancomloop v7.2.0 does not loop correctly, previous version works fine

### ISSUE THREAD

**Issue by nickdylla** [nuriamw/micro4all#5] opened 2022-08-08 21:56 UTC
Hi, love this ANCOM-BC wrapper. Unfortunately, the current version does not loop properly...the outputted dataframe does not store all possible combinations, it just stores something similar to the ANCOM-BC default result where it's only one group being compared to others, even though 4 objects are displayed. Very simply:

```
groups = c("A", "B", "C")
df <- ancomloop(input_object_phyloseq, grouping = "groups")

df

$A AvsB
$B BvsA
$C CvsA
$D DvsA
```

I went back and used the previous version of the `ancomloop` function and it worked properly (committed Apr 25, #603a2ac).

```
$A AvsB AvsC AvsD
$B BvsA BvsC BvsD
$C CvsA CvsB CvsD
$D DvsA DvsB DvsC
```

Also, it would be great to reduce the redundancy, something like this:

```
$A AvsB AvsC AvsD
$B BvsC BvsD
$C CvsD
```

**Comment by nuriamw** [comment] 2022-08-12 08:37
Hi! Thank you for your comments, happy to hear that you find it useful. In the example you provided, I see that you may have misused the argument "grouping". The function is designed in a way that the grouping argument should be the name of the variable of interest that is used to group the samples. Imagine we want to compare trees from three different locations. Then, "grouping" would be "location", that is, the variable in metadata that includes the three locations to study (location1, location2 and location3, let's say), each of them assigned to multiple samples. 
I have checked if the new ancomloop version is working with my data and it went well. I think it will be useful if you send me your session info, in case there is any difference in some packages versions that could be leading to some problems. 

Hope the explanation was clear enough 😊

Best wishes,
Nuria.

**Comment by nuriamw** [comment] 2022-09-02 13:05
Hi again @nickdylla!  It would be nice to recieve an answer in order to fix it or close the issue 😉

Best regards,
Nuira.

**Comment by nickdylla** [comment] 2022-09-02 14:11
Hi @nuriamw,

Here's the sessionInfo()
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Biobase_2.54.0         tidyr_1.1.4            splines_4.1.1         
 [4] jsonlite_1.8.0         foreach_1.5.2          carData_3.0-4         
 [7] paletteer_1.4.0.9000   assertthat_0.2.1       stats4_4.1.1          
[10] phyloseq_1.38.0        GenomeInfoDbData_1.2.7 cellranger_1.1.0      
[13] pillar_1.6.4           backports_1.2.1        lattice_0.20-45       
[16] glue_1.6.2             ggsignif_0.6.3         XVector_0.34.0        
[19] colorspace_2.0-2       Matrix_1.3-4           plyr_1.8.6            
[22] pkgconfig_2.0.3        broom_0.7.9            haven_2.4.3           
[25] zlibbioc_1.40.0        purrr_0.3.4            scales_1.1.1          
[28] openxlsx_4.2.4         rio_0.5.27             tibble_3.1.6          
[31] mgcv_1.8-38            generics_0.1.1         IRanges_2.28.0        
[34] car_3.0-11             ggplot2_3.3.5          ellipsis_0.3.2        
[37] ggpubr_0.4.0           pacman_0.5.1           BiocGenerics_0.40.0   
[40] cli_3.3.0              survival_3.2-13        magrittr_2.0.2        
[43] crayon_1.4.1           readxl_1.3.1           fansi_0.5.0           
[46] nlme_3.1-153           MASS_7.3-54            rstatix_0.7.0         
[49] forcats_0.5.1          foreign_0.8-81         vegan_2.5-7           
[52] tools_4.1.1            data.table_1.14.2      hms_1.1.1             
[55] lifecycle_1.0.1        stringr_1.4.0          Rhdf5lib_1.16.0       
[58] S4Vectors_0.32.0       munsell_0.5.0          cluster_2.1.2         
[61] ggsci_2.9              zip_2.2.0              Biostrings_2.62.0     
[64] ade4_1.7-18            compiler_4.1.1         GenomeInfoDb_1.30.0   
[67] rlang_1.0.4            rhdf5_2.38.0           grid_4.1.1            
[70] RCurl_1.98-1.5         rhdf5filters_1.6.0     iterators_1.0.13      
[73] biomformat_1.22.0      rstudioapi_0.13        igraph_1.2.7          
[76] bitops_1.0-7           multtest_2.50.0        gtable_0.3.0          
[79] codetools_0.2-18       abind_1.4-5            DBI_1.1.1             
[82] curl_4.3.2             rematch2_2.1.2         reshape2_1.4.4        
[85] R6_2.5.1               dplyr_1.0.8            utf8_1.2.2            
[88] permute_0.9-5          ape_5.5                stringi_1.7.5         
[91] parallel_4.1.1         Rcpp_1.0.7             vctrs_0.4.1.9000      
[94] tidyselect_1.1.1  
```

What I struggle to follow is why the previous `ancomloop` version (committed Apr 25, #603a2ac) works properly but the latest version does not. Unless the latest version handles the "grouping" differently, there must be something else happening. I tried diving into the commit differences, but wasn't able to find it myself.

**Comment by nuriamw** [comment] 2022-09-05 10:21
Hi @nickdylla,

I was checking the differences in packages and couldn't find the problem. Your phyloseq version is older but as long as I've seen, this shouldn't be an issue. 

It would be nice if you could try to use ancomloop function on a **demo dataset** just to make sure that the problem is not in your data. You can do that as follows:

```
library(phyloseq)
data(GlobalPatterns)
GP <- GlobalPatterns

phylum1<- tax_glom(GP, taxrank = "Genus")

phylum1samples <- subset_samples(Phylum1 , SampleType=="Feces"|SampleType=="Freshwater"|SampleType=="Soil")

ancom <- ancomloop(input_object_phyloseq = phylum1samples , grouping = "SampleType", ancom.options = list(global=FALSE, struc_zero=TRUE),out.unclassified = TRUE, tax.level="Phylum")

View(ancom[[1]])
```
The last change I made to  ancomloop function is related with [issue#4](https://github.com/nuriamw/micro4all/issues/4). The new version of ANCOMBC changed the name of the **beta index to lfc**. Because of that, I had to change ancomloop to select the elements of ANCOMBC **by their position** (you'll find it now in the function as **lfc <- table_ancom[[1]])**). No other changes related with grouping were applied. 



Cheers,

Nuria

**Closed as completed** 2024-09-09 09:36 UTC
